const button = {
  type: 'Button',
  info: '按钮',
  field: 'button',
  class: 'button-container',
  // 可配置项
  configsList: [
    {
      header: 'Button Color Default',
      cssType: 'color',
      value: 'ButtonColor',
      groups: [
        {
          type: 'colorPicker',
          field: 'button-default-color',
          buttonType:'default',
          info: '默认 颜色',
          title: '默认 颜色',
          content: '测试文字',
        },
        {
          type: 'colorPicker',
          field: 'button-default-color-text',
          buttonType:'default',
          info: '默认 文字颜色',
          title: '默认 文字颜色',
          content: '测试文字',
        },
        {
          type: 'colorPicker',
          field: 'button-default-background-hover',
          buttonType:'default',
          info: '默认 背景悬浮颜色',
          title: '默认 背景悬浮颜色',
          content: '测试文字',
        },
        {
          type: 'colorPicker',
          field: 'button-default-background-active',
          buttonType:'default',
          info: '默认 背景悬浮颜色 active',
          title: '默认 背景悬浮颜色 active',
          content: '测试文字',
        },
      ]
    },
    {
      header: 'Button Color Theme',
      cssType: 'color',
      value: 'ButtonColor',
      groups: [
        {
          type: 'colorPicker',
          field: 'button-primary-color',
          buttonType:'primary',
          info: '主题色 文字颜色',
          title: '主题色 文字颜色',
          content: '测试文字',
        },
        {
          type: 'colorPicker',
          field: 'color-primary-light',
          buttonType:'primary',
          info: '主题色 1级浅色 文字颜色',
          title: '主题色 1级浅色 文字颜色',
          content: '测试文字',
        },
        {
          type: 'colorPicker',
          field: 'color-primary-lighter',
          buttonType:'primary',
          info: '主题色 2级浅色 文字颜色',
          title: '主题色 2级浅色 文字颜色',
          content: '测试文字',
        },
        {
          type: 'colorPicker',
          field: 'color-primary-lightest',
          buttonType:'primary',
          info: '主题色 3级浅色 文字颜色',
          title: '主题色 3级浅色 文字颜色',
          content: '测试文字',
        },
      ]
    },
    {
      header: 'Button Color Others',
      cssType: 'color',
      value: 'ButtonColor',
      groups: [
        {
          type: 'colorPicker',
          field: 'button-primary-hover',
          buttonType:'primary',
          info: '主题色 鼠标悬浮时颜色',
          title: '主题色 鼠标悬浮时颜色',
          content: '测试文字',
        },
        {
          type: 'colorPicker',
          field: 'button-primary-active',
          buttonType:'primary',
          info: '主题色 激活颜色',
          title: '主题色 激活颜色',
          content: '测试文字',
        },
        {
          type: 'colorPicker',
          field: 'button-primary-disable',
          buttonType:'primary',
          info: '主题色 禁用颜色',
          title: '主题色 禁用颜色',
          content: '测试文字',
        },
        {
          type: 'colorPicker',
          field: 'tag-background-active',
          buttonType:'primary',
          info: '标签底色',
          title: '标签底色',
          content: '测试文字',
        },
        {
          type: 'colorPicker',
          field: 'button-primary-plain',
          buttonType:'primary',
          info: '主题色 朴素模式下颜色',
          title: '主题色 朴素模式下颜色',
          content: '测试文字',
        },
        {
          type: 'colorPicker',
          field: 'button-primary-disabled-plain',
          buttonType:'primary',
          info: '主题色 朴素主题禁止下颜色 ',
          title: '主题色 朴素主题禁止下颜色 ',
          content: '测试文字',
        },
        {
          type: 'colorPicker',
          field: 'button-primary-plain-hover',
          buttonType:'primary',
          info: '主题色 朴素悬浮颜色',
          title: '主题色 朴素悬浮颜色',
          content: '测试文字',
        },
        {
          type: 'colorPicker',
          field: 'button-primary-plain-active',
          buttonType:'primary',
          info: '主题色 朴素激活颜色',
          title: '主题色 朴素激活颜色',
          content: '测试文字',
        },
      ]
    },
  ],
  // 可配置项数据
  configsDatas: {
    'button-default-color': '#888',
    'button-primary-color': '#1E5EFF',
    'color-primary-light': '#3c86ff',
    'color-primary-lighter': '#3774EE',
    'color-primary-lightest': '#348BF5',
    'button-primary-hover': '#5d9bff',
    'button-primary-active': '#5d9bff',
    'button-primary-disable': '#97BCF9',
    'button-primary-plain': '#bbb',
    'button-primary-disabled-plain': '#e6e9ef',
    'button-primary-plain-hover': '#EDF4FF',
    'button-primary-plain-active': '#D3E2FA',
    'button-default-color-text': '#666f80',
    'button-default-background-hover': '#F6F7F7',
    'button-default-background-active': '#EFF0F1',
    'tag-background-active': '#E3EDFC',
  },
};

export default button;